power=read.table("household_power_consumption.txt", sep=";", na.strings="?", header=TRUE)
trimmed_power=power[grepl("^(1|2)\\/2\\/2007",power$Date),]
trimmed_power$Date <- as.Date(trimmed_power$Date , "%d/%m/%Y")
trimmed_power$DateTime <- strptime(paste(trimmed_power$Date, trimmed_power$Time, sep=" "), "%Y-%m-%d %H:%M:%S")
png("plot3.png", width=480, height=480, units="px")
plot(trimmed_power$DateTime, trimmed_power$Sub_metering_1, xlab = "", ylab = "Energy sub metering", type = "l", col="Black")
lines(trimmed_power$DateTime, trimmed_power$Sub_metering_2, col="Red")
lines(trimmed_power$DateTime, trimmed_power$Sub_metering_3, col="Blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),col=c("Black", "Red", "Blue"), lty=1)
dev.off()
